name: hummus_admin_panel
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  get: ^4.6.5
  shared_preferences: ^2.2.0
  get_storage: ^2.1.1
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.4
  expandable: ^5.0.1
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  google_maps_flutter: ^2.3.1
  google_maps_flutter_web: ^0.5.8
  http: ^1.0.0
  image_picker: ^1.0.4
  either_dart: ^1.0.0
  logger: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal_Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal/Tajawal_Regular.ttf
          weight: 500
        - asset: assets/fonts/Tajawal/Tajawal_Bold.ttf
          weight: 700
