name: hummus_admin_panel
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  shared_preferences: ^2.2.0
  get_storage: ^2.1.1
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.4
  expandable: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal_Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal/Tajawal_Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal/Tajawal_Bold.ttf
          weight: 700
